# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "npm" # See documentation for possible values
    directory: "/frontend" # Location of package manifests
    schedule:
      interval: "weekly"
      time: "07:00"
      timezone: "Europe/Warsaw"
    allow:
      - dependency-type: "direct"
    commit-message:
      prefix: "[package.json] "
    labels:
      - "package.json"
      - "dependencies"
    # lower this value down after couple initial package bumps
    open-pull-requests-limit: 3
    
  - package-ecosystem: "npm" # See documentation for possible values
    directory: "/backend" # Location of package manifests
    schedule:
      interval: "weekly"
      time: "07:00"
      timezone: "Europe/Warsaw"
    allow:
      - dependency-type: "direct"
    commit-message:
      prefix: "[package.json] "
    labels:
      - "package.json"
      - "dependencies"
    # lower this value down after couple initial package bumps
    open-pull-requests-limit: 3

